log:
  level: INFO

api:
  # "insecure config is true will allow using IP & Http protocol connect Traefik Dashboard. Don't do this in production! "
  insecure: true
  dashboard: true

entryPoints:
  # "for our official websites"
  web:
    address: :80
    # "(Optional) Redirect to HTTPS"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
#    forwardedHeaders:
#     trustedIPs:
#        - "127.0.0.1/32" # localhost
#        - "192.168.0.0/16" # stand-alone after 172.16.0.0/12 is exhausted
#      insecure: true

  # "for our dev websites"
#  webdev:
#    address: :8443

  # "for local api dev"
#  apidev:
#    address: :8000

  # "for local frontend dev"
#  localwebdev:
#    address: :9000

providers:
  # "provide traefik docker sock for listen and watch"
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  # "provide traefik SubDirectory(Path) config"
  file:
    # "watch for dynamic configuration changes"
    directory: /
    watch: true
  
# "Configure your CertificateResolver here"
certificatesResolvers:
  lets-encr:
    acme:
      storage: letsencrypt/acme.json
      email: joerenyu93@gmail.com 
      
      # "letsencrypt certificate official server, don't use this server for multiple apply certificates at the same time, if do will trigger RateLimit, this server is not for test apply certificates"
      caServer: https://acme-v02.api.letsencrypt.org/directory

      # "letsencrypt certificate test server, no RateLimit"
#      caServer: https://acme-staging-v02.api.letsencrypt.org/directory

#      dnsChallenge:
#        provider: cloudflare

      httpChallenge:
        entryPoint: web

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
       # Recommended ciphers for TLSv1.2
       - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
       - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
       - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
       # Recommended ciphers for TLSv1.3
       - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
       - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
       - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    tlsv13only:
      minVersion: VersionTLS13
# "Subdirectory(Path) config"

http:
  middlewares:
    traefik-compress:
      compress: {}
    secure-headers:
#      forwardAuth:
#        address: "https://dev-student.overseas.ncnu.edu.tw/auth"
#        trustForwardHeader: true
      headers:
        accesscontrolallowmethods: 
          - GET
          - POST
        accessControlMaxAge: 100
        addVaryHeader: true
        hostsProxyHeaders: "X-Forwarded-Host"
#        sslRedirect: true
        frameDeny: true
        browserXssFilter: true
        sslProxyHeaders:
          X-Forwaeded-Proto: "https"
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 63072000
        contentTypeNosniff: true
        forceSTSHeader: true
        referrerPolicy: "strict-origin-when-cross-origin"
        contentSecurityPolicy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://stackpath.bootstrapcdn.com https://maxcdn.bootstrapcdn.com https://cdn.jsdelivr.net/gh/CarlosBonetti/ https://cdn.jsdelivr.net/bootstrap-sortable/ https://cdnjs.cloudflare.com/ajax/libs/popper.js/ https://cdnjs.cloudflare.com/ajax/libs/tether/ https://cdnjs.cloudflare.com/ajax/libs/moment.js/ https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/ https://cdnjs.cloudflare.com/ajax/libs/vue/ https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/ https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/ https://cdnjs.cloudflare.com/ajax/libs/js-sha256/ https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/ https://code.jquery.com https://cdn.polyfill.io https://rawgit.com https://www.gstatic.com https://www.google.com/recaptcha/ https://www.googletagmanager.com https://www.google-analytics.com https://ajax.googleapis.com https://connect.facebook.net; style-src 'self' 'unsafe-inline' https://stackpath.bootstrapcdn.com https://maxcdn.bootstrapcdn.com https://cdnjs.cloudflare.com https://cdn.jsdelivr.net https://www.gstatic.com https://use.fontawesome.com https://code.jquery.com; font-src 'self' https://cdnjs.cloudflare.com https://use.fontawesome.com; frame-src https://dev-api.overseas.ncnu.edu.tw:* https://www.googletagmanager.com https://www.facebook.com https://www.google.com; frame-ancestors https://*.overseas.ncnu.edu.tw https://www.googletagmanager.comi https://www.google.com; object-src https://dev-api.overseas.ncnu.edu.tw:*; img-src 'self' https://api.overseas.ncnu.edu.tw:* https://www.google-analytics.com https://cmn-hant.overseas.ncnu.edu.tw:* data:; connect-src 'self' https://dev-api.overseas.ncnu.edu.tw:*;
#        accessControlAllowOriginList: '*'
#          - https://dev-api.overseas.ncnu.edu.tw
#        contentSecurityPolicy:  script-src 'unsafe-inline' 'self' https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.11.2/sweetalert2.min.js https://cdnjs.cloudflare.com/ajax/libs/js-sha256/0.9.0/sha256.js https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.26.0/polyfill.min.js https://code.jquery.com/jquery-3.6.0.min.js https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js https://www.google.com/recaptcha/api.js?render=6LcmL6kaAAAAAAn1nqIqFkmDmI_F0NOv8Z3zMyX9 https://www.gstatic.com/recaptcha/releases/ovmhLiigaw4D9ujHYlHcKKhP/recaptcha__en.js https://www.googletagmanager.com/gtm.js?id=GTM-NXCCHWB https://www.google-analytics.com/analytics.js https://www.gstatic.com/recaptcha/releases/a9s0j4pCVT6gaTEkLiFbtZPH/recaptcha__en.js https://code.jquery.com/jquery-3.1.1.min.js https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js https://cdn.jsdelivr.net/gh/CarlosBonetti/jquery-loading/dist/jquery.loading.min.js https://rawgit.com/emn178/js-sha256/master/src/sha256.js
#    addpaths:
#        stripPrefix:
#            prefixes:
#                - "/survey"
#                - "/mrbs"
#            forceSlash: true
