log:
  level: INFO

api:
  # "insecure config is true will allow using IP & Http protocol connect Traefik Dashboard. Don't do this in production! "
  insecure: true
  dashboard: true

entryPoints:
  # "for our official websites"
  web:
    address: :80
    # "(Optional) Redirect to HTTPS"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

  # "for our dev websites"
  webdev:
    address: :8443

  # "for local api dev"
#  apidev:
#    address: :8000

  # "for local frontend dev"
#  localwebdev:
#    address: :9000

providers:
  # "provide traefik docker sock for listen and watch"
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  # "provide traefik SubDirectory(Path) config"
  file:
    # "watch for dynamic configuration changes"
    directory: /
    watch: true
  
# "Configure your CertificateResolver here"
certificatesResolvers:
  lets-encr:
    acme:
      storage: letsencrypt/acme.json
      email: ocacoyvtp@gmail.com
      
      # "letsencrypt certificate official server, don't use this server for multiple apply certificates at the same time, if do will trigger RateLimit, this server is not for test apply certificates"
      caServer: https://acme-v02.api.letsencrypt.org/directory

      # "letsencrypt certificate test server, no RateLimit"
#      caServer: https://acme-staging-v02.api.letsencrypt.org/directory

#      dnsChallenge:
#        provider: cloudflare

      httpChallenge:
        entryPoint: web

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
       # Recommended ciphers for TLSv1.2
       - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
       - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
       - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
       # Recommended ciphers for TLSv1.3
       - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
       - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
       - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    tlsv13only:
      minVersion: VersionTLS13

http:
  middlewares:
    ipwhitelist:
      ipWhiteList:
        sourceRange:
          - "163.22.18.9"
    traefik-compress:
      compress: {}
#        excludedContentTypes:
#          - text/html
    cors:
      headers:
        accessControlAllowOriginList:
          - "https://api.oyvtp.org"
          - "https://student.oyvtp.org"
          - "https://school.oyvtp.org"
          - "https://office.oyvtp.org"
          - "https://api.oyvtp.org:8443"
          - "https://student.oyvtp.org:8443"
          - "https://school.oyvtp.org:8443"
          - "https://office.oyvtp.org:8443"
        accessControlAllowMethods:
          - GET
          - POST
          - DELETE
          - PUT
          - PATCH
        accessControlAllowHeaders: 
          - "Content-Type"
          - "Authorization"
        accessControlAllowCredentials: true
        accessControlMaxAge: 100
        addVaryHeader: true
    secure-headers:
      headers:
        accessControlMaxAge: 100
        addVaryHeader: true
        hostsProxyHeaders: "X-Forwarded-Host"
#        sslRedirect: true
        frameDeny: true
        browserXssFilter: true
        sslProxyHeaders:
          X-Forwaeded-Proto: "https"
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 63072000
        contentTypeNosniff: true
        forceSTSHeader: true
        referrerPolicy: "strict-origin-when-cross-origin"
        contentSecurityPolicy: default-src 'self'; manifest-src 'self' https://api.oyvtp.org:*/; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://stackpath.bootstrapcdn.com https://maxcdn.bootstrapcdn.com https://cdn.jsdelivr.net/gh/CarlosBonetti/ https://cdn.jsdelivr.net/bootstrap-sortable/ https://cdnjs.cloudflare.com/ajax/libs/popper.js/ https://cdnjs.cloudflare.com/ajax/libs/tether/ https://cdnjs.cloudflare.com/ajax/libs/moment.js/ https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/ https://cdnjs.cloudflare.com/ajax/libs/vue/ https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/ https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/ https://cdnjs.cloudflare.com/ajax/libs/js-sha256/ https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/ https://code.jquery.com https://cdn.polyfill.io https://rawgit.com https://www.google.com/recaptcha/ https://connect.facebook.net https://cdnjs.cloudflare.com/ajax/libs/date-fns/ https://cdnjs.cloudflare.com/ajax/libs/xlsx/ https://cdn.jsdelivr.net/gh/emn178/ https://cdnjs.cloudflare.com/ajax/libs/jquery-easy-loading/ https://cdnjs.cloudflare.com/ajax/libs/bootstrap-filestyle/ https://www.googletagmanager.com/gtm.js https://www.google-analytics.com/analytics.js https://www.gstatic.com/recaptcha/releases/ https://cdnjs.cloudflare.com/ajax/libs/paginationjs/ https://cdnjs.cloudflare.com/ajax/libs/jschardet/ https://cdnjs.cloudflare.com/ajax/libs/webrtc-adapter/ https://cdnjs.cloudflare.com/ajax/libs/quagga/ https://www.googletagmanager.com/gtag/ https://cdnjs.cloudflare.com/ajax/libs/jqueryui/; style-src 'self' 'unsafe-inline' https://stackpath.bootstrapcdn.com https://maxcdn.bootstrapcdn.com https://cdnjs.cloudflare.com https://cdn.jsdelivr.net https://www.gstatic.com https://use.fontawesome.com https://code.jquery.com; font-src 'self' https://cdnjs.cloudflare.com https://use.fontawesome.com data:; frame-src https://api.oyvtp.org:* https://www.googletagmanager.com https://www.facebook.com https://www.google.com; frame-ancestors https://*.oyvtp.org https://www.googletagmanager.com https://www.google.com; object-src 'self' https://api.oyvtp.org:*/editors/add-new-department-apply-list/file/ https://api.oyvtp.org:*/admins/school-apply-list/ https://api.oyvtp.org:*/young-associate/admission-paper/; img-src 'self' https://api.oyvtp.org:* https://www.google-analytics.com https://api.oyvtp.org:*/editors/add-new-department-apply-list/file/ data:; connect-src 'self' https://api.oyvtp.org:* https://www.google-analytics.com/j/ https://stats.g.doubleclick.net/j/ https://www.google-analytics.com/g/collect; worker-src 'self' blob:;